[[GenICamRuntime]]
arch = "aarch64"
git-tree-sha1 = "87af9816f3f93f166fa4def99ae1cf1e06ce528f"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "4bc4db3e4758d957a273b94e997e8fc1e478b09e3e620b10960a6a048e11af58"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.aarch64-linux-gnu.tar.gz"
[[GenICamRuntime]]
arch = "aarch64"
git-tree-sha1 = "87af9816f3f93f166fa4def99ae1cf1e06ce528f"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "4bc4db3e4758d957a273b94e997e8fc1e478b09e3e620b10960a6a048e11af58"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.aarch64-linux-musl.tar.gz"
[[GenICamRuntime]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c953dfc38ab44265cc2d6c02b6a3181bfb14ced3"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "16049f0d2c18d28306867886f9661d26583385c550c98f307bf95e75f6c2f07e"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.armv6l-linux-gnueabihf.tar.gz"
[[GenICamRuntime]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c953dfc38ab44265cc2d6c02b6a3181bfb14ced3"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "16049f0d2c18d28306867886f9661d26583385c550c98f307bf95e75f6c2f07e"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.armv6l-linux-musleabihf.tar.gz"
[[GenICamRuntime]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c953dfc38ab44265cc2d6c02b6a3181bfb14ced3"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "16049f0d2c18d28306867886f9661d26583385c550c98f307bf95e75f6c2f07e"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.armv7l-linux-gnueabihf.tar.gz"
[[GenICamRuntime]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c953dfc38ab44265cc2d6c02b6a3181bfb14ced3"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "16049f0d2c18d28306867886f9661d26583385c550c98f307bf95e75f6c2f07e"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.armv7l-linux-musleabihf.tar.gz"
[[GenICamRuntime]]
arch = "i686"
git-tree-sha1 = "1dfb0cb136c9e75b709ccb44cb421609af1fe0b7"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "0ba43e58d89f254c2d770eae02284d9944041a321ccf9f223f007d182e27a2c4"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.i686-linux-gnu.tar.gz"
[[GenICamRuntime]]
arch = "i686"
git-tree-sha1 = "1dfb0cb136c9e75b709ccb44cb421609af1fe0b7"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "0ba43e58d89f254c2d770eae02284d9944041a321ccf9f223f007d182e27a2c4"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.i686-linux-musl.tar.gz"
[[GenICamRuntime]]
arch = "i686"
git-tree-sha1 = "37ca056f4374d8aaed37dbd1e67caa73c0f96bc6"
os = "windows"

    [[GenICamRuntime.download]]
    sha256 = "1bd0dd3f82eb9dd97aa3f3637a97bd976d0eecf8678c6be63238578b08761fad"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.i686-w64-mingw32.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "d8ea923a3bf1c9adb3d352c8b171979968653b79"
os = "macos"

    [[GenICamRuntime.download]]
    sha256 = "621c652c6a7da1fb2f939a147fba1aa856c4a053a106737fa04d918fcc4c0175"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.x86_64-apple-darwin.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "eea8a3dd2a4f2052a9e39002d909b1a55017daca"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "614afc0ed5901e53146c8cd5dc27bb084bdeee97f2786a8aabbb58bb9dd5a910"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.x86_64-linux-gnu.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "eea8a3dd2a4f2052a9e39002d909b1a55017daca"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "614afc0ed5901e53146c8cd5dc27bb084bdeee97f2786a8aabbb58bb9dd5a910"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.x86_64-linux-musl.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "f69cd32298afafa63c54993f15c5ad765782bf63"
os = "windows"

    [[GenICamRuntime.download]]
    sha256 = "a9b663c4bef1e8d728815b2620fbb9a9bc6c8152a6c8e551ab8e811dabfc86bf"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.1.0+0/GenICamRuntime.v3.1.0.x86_64-w64-mingw32.tar.gz"
