[[GenICamRuntime]]
arch = "aarch64"
git-tree-sha1 = "a31592b735da535741d52e31e2473f4f65e551d8"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "0b660508b71a0180778f2531ce1aa8621a6f3ac7064cf5219baa596af0958b50"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.aarch64-linux-gnu.tar.gz"
[[GenICamRuntime]]
arch = "aarch64"
git-tree-sha1 = "a31592b735da535741d52e31e2473f4f65e551d8"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "0b660508b71a0180778f2531ce1aa8621a6f3ac7064cf5219baa596af0958b50"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.aarch64-linux-musl.tar.gz"
[[GenICamRuntime]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "496c23a19ff65151436e629223b8cb162d854895"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "67f03ff38cfeff457ac03758f56571780ea7ff008bc38382e53411bbb347d15f"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.armv6l-linux-gnueabihf.tar.gz"
[[GenICamRuntime]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "496c23a19ff65151436e629223b8cb162d854895"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "67f03ff38cfeff457ac03758f56571780ea7ff008bc38382e53411bbb347d15f"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.armv6l-linux-musleabihf.tar.gz"
[[GenICamRuntime]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "496c23a19ff65151436e629223b8cb162d854895"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "67f03ff38cfeff457ac03758f56571780ea7ff008bc38382e53411bbb347d15f"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.armv7l-linux-gnueabihf.tar.gz"
[[GenICamRuntime]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "496c23a19ff65151436e629223b8cb162d854895"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "67f03ff38cfeff457ac03758f56571780ea7ff008bc38382e53411bbb347d15f"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.armv7l-linux-musleabihf.tar.gz"
[[GenICamRuntime]]
arch = "i686"
git-tree-sha1 = "69e8f6597826ea9dc39cdcaa099c9ebb4d7265a2"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "06e7fa62440f6d1ebcc27e6b31093ab7fb0dab49645b7958785769d408d0eb6f"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.i686-linux-gnu.tar.gz"
[[GenICamRuntime]]
arch = "i686"
git-tree-sha1 = "69e8f6597826ea9dc39cdcaa099c9ebb4d7265a2"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "06e7fa62440f6d1ebcc27e6b31093ab7fb0dab49645b7958785769d408d0eb6f"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.i686-linux-musl.tar.gz"
[[GenICamRuntime]]
arch = "i686"
git-tree-sha1 = "6ae665c92f86fb6ffc53451e7c2ee9d193e14928"
os = "windows"

    [[GenICamRuntime.download]]
    sha256 = "9cc17d52e1cc9ab5a64e4c645babca0e7dfb1fa75390e5bcd9c668c941810580"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.i686-w64-mingw32.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "363428ebec791313938f5d657e66262903c58590"
os = "macos"

    [[GenICamRuntime.download]]
    sha256 = "567c774dbcecf4a38b133a6054c5cf39cc0eae5a1012a715dd95eb02989372b5"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.x86_64-apple-darwin.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "80f58da4fe33de8766221f0332b033fcabd56fc9"
libc = "glibc"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "3355c1d8bf23a2be1f082a9ca3a3855947592ef643c937d48c76dae1533cb2c1"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.x86_64-linux-gnu.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "80f58da4fe33de8766221f0332b033fcabd56fc9"
libc = "musl"
os = "linux"

    [[GenICamRuntime.download]]
    sha256 = "3355c1d8bf23a2be1f082a9ca3a3855947592ef643c937d48c76dae1533cb2c1"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.x86_64-linux-musl.tar.gz"
[[GenICamRuntime]]
arch = "x86_64"
git-tree-sha1 = "9e198c6276083394637dff03feeaaad4df7082c2"
os = "windows"

    [[GenICamRuntime.download]]
    sha256 = "bb843ff7afd533efc7b7e0c47de517bc9af94734e2802f8ec76402d584591464"
    url = "https://github.com/JuliaBinaryWrappers/GenICamRuntime_jll.jl/releases/download/GenICamRuntime-v3.3.0+0/GenICamRuntime.v3.3.0.x86_64-w64-mingw32.tar.gz"
