# Autogenerated wrapper script for GenICamRuntime_jll for x86_64-w64-mingw32
export libGCBase, libGenApi, libLog, libMathParser, libNodeMapData, libXmlParser

JLLWrappers.@generate_wrapper_header("GenICamRuntime")
JLLWrappers.@declare_library_product(libGCBase, "GCBase_MD_VC141_v3_3.dll")
JLLWrappers.@declare_library_product(libGenApi, "GenApi_MD_VC141_v3_3.dll")
JLLWrappers.@declare_library_product(libLog, "Log_MD_VC141_v3_3.dll")
JLLWrappers.@declare_library_product(libMathParser, "MathParser_MD_VC141_v3_3.dll")
JLLWrappers.@declare_library_product(libNodeMapData, "NodeMapData_MD_VC141_v3_3.dll")
JLLWrappers.@declare_library_product(libXmlParser, "XmlParser_MD_VC141_v3_3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libGCBase,
        "bin\\GCBase_MD_VC141_v3_3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGenApi,
        "bin\\GenApi_MD_VC141_v3_3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libLog,
        "bin\\Log_MD_VC141_v3_3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMathParser,
        "bin\\MathParser_MD_VC141_v3_3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libNodeMapData,
        "bin\\NodeMapData_MD_VC141_v3_3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libXmlParser,
        "bin\\XmlParser_MD_VC141_v3_3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
