# Autogenerated wrapper script for GenICamRuntime_jll for x86_64-apple-darwin
export libGCBase, libGenApi, libLog, libMathParser, libNodeMapData, libXmlParser

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("GenICamRuntime")
JLLWrappers.@declare_library_product(libGCBase, "@rpath/libGCBase_clang61_v3_1.dylib")
JLLWrappers.@declare_library_product(libGenApi, "@rpath/libGenApi_clang61_v3_1.dylib")
JLLWrappers.@declare_library_product(libLog, "@rpath/libLog_clang61_v3_1.dylib")
JLLWrappers.@declare_library_product(libMathParser, "@rpath/libMathParser_clang61_v3_1.dylib")
JLLWrappers.@declare_library_product(libNodeMapData, "@rpath/libNodeMapData_clang61_v3_1.dylib")
JLLWrappers.@declare_library_product(libXmlParser, "@rpath/libXmlParser_clang61_v3_1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libGCBase,
        "lib/libGCBase_clang61_v3_1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libGenApi,
        "lib/libGenApi_clang61_v3_1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libLog,
        "lib/libLog_clang61_v3_1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMathParser,
        "lib/libMathParser_clang61_v3_1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libNodeMapData,
        "lib/libNodeMapData_clang61_v3_1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libXmlParser,
        "lib/libXmlParser_clang61_v3_1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
